wasmer.toml
[package]
name = "tccgit/prototipo"
version = "0.1.0"
description = "App PHP/JS"

[scripts]
# Tenta instalar as dependências JS (npm install) E PHP (composer install)
# O operador "&&" garante que um comando só executa se o anterior for bem-sucedido.
build = "npm install && composer install" 

# Inicia o servidor PHP embutido, que servirá todos os seus arquivos.
start = "php -t . -S 0.0.0.0:8080"